mineral-ui/mineral-ui

- scripts/package/build.sh
Update build script to NOT build es modules for the site package as they are unnecessary
closes #24 
* Ran `npm run build` at root level and verified that `site` package no longer contains `dist/es` folder, but other packages still do.
* Automated tests passing
* Site demo works locally
Update to build script
> build(*): Don’t build es modules in site package

- package.json
- packages/site/public/CNAME
- packages/site/webpack.config.js
Site deploy now includes public assets
* Add CNAME to site public assets
* Update site webpack to copy all files from public to dist
closes #23 
* I ran `npm run build` in the site package and verified that the `dist` directory contains the CNAME file.
* I ran `npm run deploy:site` and verified that the `mineral-ui.github.io` repo contains the CNAME file
> feat(site): Site deploy now includes public assets

- README.md
Due to the casing here:
```
import Hello from '@mineral-ui/Hello';
import World from '@mineral-ui/World';
```
I'm seeing an eslint error related to `import/no-unresolved`, which is a part of `eslint-config-airbnb`.
It's a quick fix, which just involves either converting the casing of `@mineral-ui/Hello` to `@mineral-ui/hello` or renaming your component folders to be capitalized(the solution I'd recommend).
Within the Phoenix console, we utilize the [`eslint-config`](https://github.com/CAAPIM/eslint-config-ca/)  package that we, the Web Client Team, made. This configuration extends functionality from `eslint-config-airbnb` and includes other widely accepted eslint rules. 
The `Mineral-UI` project should work with(and probably use) our `eslint-config` package, as it enforces many widely …
> [README] Update imports to avoid airbnb/eslint conflict: "import/no-unresolved"

- CONTRIBUTING.md
Update contributing docs as I am testing [cla-assistant](http://cla-assistant.io) integration.
__Additional Notes:__
* greenkeeper bot imported into cla-assistant
* If desired, can import other team members so that they do not have to accept
* Applied to whole org so affects all repos
* CA CLA obtained from APIM - and now lives at https://gist.github.com/mineral-ci/e9763fc3bc762425ff0d408658fbfd82
* Added link to CLA to Contributing.md
* Login with mineral-ci user at https://cla-assistant.io/
For legal reasons, contributors need to sign a contributor license agreement
connects #42
Manual testing on existing PR's
documentation and 3rd party service integration
> [docs]: Update contributing docs

- .eslintrc
- package.json
Add and configure [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) package
Sometimes `eslint` and `prettier` get confused and caught in a loop where one of them will always report an error and want to update some formatting.  Fixing the formatting will then cause the other one to report an error.
This package disables all rules that are unnecessary or might conflict with prettier.
I found a conflicting situation, then enabled this plugin and it worked as expected.
Added a new package that only affects development/build environment
> chore(eslint): Avoid conflicts between eslint and prettier

- .travis.yml
the `build` script already runs `bootstrap` so this will save us 3.5s on each ci run
:)
> ci(bootstrap): stop bootstrapping twice

- README.md
- packages/site/src/web/index.html
without the weights in the query, the font will fallback to a system font when you try to bold or italicize
> fix(font): add all the weights to the font download

- packages/archetype/src/__demo__/index.js
- packages/hello-world/src/__demo__/index.js
- packages/hello/src/__demo__/index.js
- packages/site/src/components/ComponentDoc.js
- packages/site/src/components/PropList.js
- packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
- packages/style-utils/src/__demo__/index.js
- packages/world/src/__demo__/index.js
Added a SubNav element and re-organized all sections into one content area.
Getting started with the re-layout according to @kylegach's style updates. We added some flags to each demo object like `behavior`, `design`, and `howToUse` that will render for each component page. 
Getting everything in place for continued PRs in this vein.
- New feature (non-breaking change which adds functionality
> feat(site): Add sub-nav to component doc page

- packages/site/src/components/ComponentDoc.js
I missed a place where I needed to alphabetize prop order
Nothing really changed, I just forgot that my editor doesn't auto-save and I missed adding some changes from an earlier PR.
- formatting change to some prop definitions
> style(site): alphabetize prop names

- packages/hello-world/src/HelloWorld.js
- packages/hello/src/Hello.js
- packages/site/src/components/ComponentDoc.js
- packages/site/src/components/ComponentDocExample.js
- packages/site/src/components/PropTable.js
- packages/site/src/components/siteTheme.js
move proptypes tables to top level of component page
the proptables used to be rendered per example, now they're only rendered once per component at the top of the page
connects #53 
ran the demo
refactor
> feat(site): move proptypes tables to top level of component page

- packages/button/src/Button.js
- packages/button/src/__demo__/examples/truncation.js
- packages/button/src/__tests__/__snapshots__/Button.spec.js.snap
- packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
Remove polished import from Button component
* Inline ellipsis/truncation styles
* Add truncation example to demo
Tried to consume the newly published Button component in another app and it complained about the `polished` import not being available in the `es` modules.  We were only using it to provide the truncation styles in the button.  No big deal, so I just removed the dependency and inlined the CSS.  As we will likely want to use polished in the future, we should figure out the correct packaging approach here.
I added a truncation example to the button demo and verified that it still works.
> [Button] Remove polished import from Button component

- package.json
- packages/site/public/404.html
- packages/site/src/web/index.js
- utils/makeWebpackConfig.js
Add support for site routing on gh-pages.  This should only be considered a temporary solution until we either prerender the site and/or switch to Netlify.
Our site package is currently deployed to Github pages as an SPA with client side routing.  With this naive approach, users must visit the root url and navigate using the in-app navigation alone.  They cannot navigate directly to a route, `components/button`, for example.  Github will give them a 404 page instead.  This PR introduces a hack that uses Github's support for a custom 404 page to capture the attempted URL, then redirect back to the root and use the saved url for routing the request.
closes #28 
Verified locally - the 404 page is now used locally by webpack instead of just redirecting to /index.html.  While not fully …
> [SITE] Add support for site routing on gh-pages

- .babelrc
- package.json
- packages/button/src/Button.js
- packages/button/src/__tests__/__snapshots__/Button.spec.js.snap
Use polished/ellipsis helper
* Use babel-plugin-polished to compile away helper, thus only the results are included in the bundle
* Update snapshots
* NOTE: The plugin will only compile away simple helpers, not functions.  We likely need to add polished as a dependency to handle other cases if usage increases.
Polished is nice and we like nice things.  Really, it just simplifies some of the styling code and makes things more readable.
* Button truncation example working properly
* Ran build:analyze in button package and it contains no references to polished
* dist/es/Button.js contains no references to polished or the ellipsis helper, just the results
* Copied the es Button source into Sombrero and it worked
* Noted that the plugin did not compile away the darken function in the site …
> [Button]: Use polished/ellipsis helper

- packages/button/src/index.js
make Button a default export for easy importing, consistent with our other components, and consistent with the Readme.
I pulled our button into a create-react-app and it errored a bunch until I destructured the import.
This has not been directly tested, but it follows the pattern of our other components, hello and world, that are allowed to use the default export.
- Bug fix: BREAKING
> fix(button): export should allow default import

- packages/component-utils/src/__tests__/generateId.spec.js
- packages/component-utils/src/generateId.js
Add `generateId` and `resetId` utils
Extracted from icon development branch.  
Immediately useful for generating unique id's for component instances, which can be used for a variety of purposes.  The `Icon` component, for example, uses it to insert a unique `id` html attribute on a child `title` element that is then targeted by an `aria-labelledby` attribute on the parent `svg` tag.
It may also prove useful in the future when doing server side rendering and ids need to be kept in sync between client and server.
* Works on the icon branch
* Automated tests added
Added new utils to component-utils
I did not document these utils as the package is currently documented a little strangely in the demo and in the readme.  We'll need to …
> [component-utils]: Add generateId and resetId utils

- packages/site/src/web/index.html
Adjust editor styles to avoid undesired page scrollbars.
Allows the content of the editor pre tags to wrap, thus avoiding the problem entirely.
closes #184
Manual cross browser testing.
> [Site]: Adjust editor styles to avoid page scrollbars

- package.json
- packages/button/src/__tests__/__snapshots__/Button.spec.js.snap
- packages/card/src/__tests__/__snapshots__/Card.spec.js.snap
Update polished dependency to latest version
Our current version of polished uses traditional dashed css property names and causes some console warnings in the browser.  Everyone that reviews our components is distracted and thrown off by them.  The latest version of polished now uses camel cased names, which will eliminate the console warnings.
Closes #95
* Verified locally in dev tools that no warnings appear in the browser console.
* Verified that polished functionality still works.
* Verified that polished is still excluded from bundles.
NOTE: I had to run jest with the `--no-cache` flag in order for it to pick up these changes locally.  CI caught the updates.  We likely need to address jest caching separately.  https://facebook.github.io/jest/docs/troubleshooting.html#caching-issues …
> Update polished to version 1.3.0

- package.json
Add `--no-cache` flag to `jest` script
I have been running into problems where jest will not detect changes and thus will not catch changes for snapshot tests, though CI has been catching them.
I am not 100% sure that this is not a local issue, but it seems a bit dangerous to leave as is, just in case.
Here is more background.
https://facebook.github.io/jest/docs/troubleshooting.html#caching-issues
Note that this likely slows down test runs though.
* Locally, jest picks up changes properly with the `--no-cache` flag set, otherwise it does not.
Update package scripts
> [Build]: Add —-no-cache flag to jest script

- packages/site/src/components/ComponentDoc.js
Use Icon component for GitHub icon
We should build the site using mineral components as they become available
Verified locally.
refactor
> [Site]: Use Icon component for GitHub icon

- package.json
if build stops the flow server, a subsequent `test` or `flow` will start it back up
> chore(scripts): stop `build` from running flow

- .babelrc
Update babel module resolution mapping
* Allows importing components from `dist/es`. e.g.`import IconHelp from '@mineral-ui/icon/dist/es/lib/IconHelp'`
* Currently needed so that mineral components like TextField can import specific icons and not bundle ALL of them
connects #137
1. npm test
2. npm run build
3. Try importing an Icon using the dist/es/lib pathing and then try build/start/test scripts.
4. There should be no errors
How I tested:
* Updated Icon import paths in Button demo and it still works
* `npm run build` works at project root and in button package
* `npm test` works at project root and in button package
* `npm start` in button package works
* Also tried in my text-input branch and verified that only the respective icons were bundled
* build …
> [build] Module resolution

- packages/component-utils/src/__demo__/index.js
- packages/site/src/components/ComponentDoc.js
- packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
Add note about undocumented props underneath the props table
The props section will now appear regardless if there are props specified for a component.  For packages that are not components, there is now a flag to hide the prop doc, called `hidePropDoc`.  Also tweaked `renderExamples` to not render as an array as it is less readable than just using a wrapper div and I could find no specific layout/css reasons to avoid it.
This is important information that consumers will want/need to know.
closes #209 
Try it out in the demo.
Minor update to site
> [Site]: Document passthrough props behavior

- CHANGELOG.md
- scripts/release.js
- utils/changelogConfig.js
Update changelog generation
* Only include things from `mineral-ui` package, not previous `@mineral-ui` packages
* Remove changelog header, as it is more trouble than it is worth
* Don’t append entries. While that kept the header, it sorted commits in reverse
I created the changelog following recent commits and it still included all previous commits from the history of the repo, which is not what we want.  We only want to show entries since the creation of the `mineral-ui` package.
1. `npm run release`
2. When prompted to publish, select **no**
3. View changelog - it should have new entries only
4. Revert local changes caused by release script.  "a git tag and 2 commits"
build - update release script for changelog generation
> Update changelog generation

- package.json
- src/Popover/Popover.js
- src/Popover/PopoverArrow.js
- src/Popover/PopoverContent.js
- src/Popover/PopoverTrigger.js
- src/Popover/__tests__/__snapshots__/Popover.spec.js.snap
Adjust default modifiers for rendering improvements on small screens
* Uses @mineral-ui/react-popper fork until issue resolved
* Still does not flip on viewport as expected/desired
Improve rendered popover placement on small screens
* Ensure basically works like before.
* Open browser devtools and switch to mobile mode.
* Open the first popover example and see that it now renders in the page, rather than off the page
> [popover] Adjust default modifiers for rendering improvements on small screens

- src/Popover/Popover.js
- src/Popover/__tests__/Popover.spec.js
- src/Popover/__tests__/__snapshots__/Popover.spec.js.snap
- src/website/app/demos/Popover/components/ScrollBox.js
- src/website/app/demos/Popover/examples/index.js
- src/website/app/demos/Popover/examples/scrolling.js
- src/website/app/demos/Popover/examples/title.js
Update Popover to flip on viewport
BREAKING CHANGE: Remove boundariesElement prop
Popover should flip to attempt to stay in view when it encounters the edge of the viewport.
1. open deploy preview and visit popover section
1. open the first popover and scroll the page so that it flips based on the viewport
- Breaking change (fix or feature that would cause existing functionality to change)
> [Popover] Flip on viewport

- src/website/app/pages/ComponentDoc/DocProps.js
some components like CardBlock don't have props of their own, and the propDocs are not generated by react-docgen. This would cause a warning in the browser console. This fix makes the prop optional.
This fix makes flowtypes consistent with documentation behavior.
1. Navigate to `/components/card-block` in dev mode.
2. There should be no warning in the console.
> [Site] make the propDoc optional

- src/website/app/Heading.js
- src/website/app/Markdown.js
- src/website/app/Paragraph.js
- src/website/index.html
Added proper shades of gray to Heading component and create a Paragraph element per the design spec.
Also add Cyrillic and Greek glyph support to Open Sans, since the site needs it in a couple of places.
We need visual consistency when comparing our Guidelines pages, and only #328 had the typography updates. This PR pulls those changes out so that there are fewer facets to think about when discussing hierarchy on the content pages.
2. Navigate to Guidelines > Theming
3. see that the h1 is "Mineral black" instead of `#000`, and the h2 is gray.
4. Markdown-generated body copy is now the `prose` font style.
> [Website] Display markdown typography according to spec

- src/website/app/PropTable.js
- src/website/app/demos/Menu/index.js
- src/website/app/demos/Popover/index.js
Adds an early return to `PropTable`’s `getPropTableRows` function that filters out any prop with a description that starts with "`@Private`".
Every once in a while, we need to pass a prop around between components that we don’t want to draw attention to by including in our prop table. We currently do this by simply deleting the prop from the `propDoc` object before passing it to `ComponentDoc`. This change makes it a more natural and less manual process.
http://hide-private-props--mineral-ui.netlify.com/components/menu#api-and-theme
1. Open the site and navigate to [Menu](http://hide-private-props--mineral-ui.netlify.com/components/menu#api-and-theme)
2. Confirm that `getItemProps` (Menu’s only private prop as of this writing) does not display in the prop table
3. Navigate to Popover and …
> [Webite] Filter out @Private props from PropTable

- src/website/app/ComponentDocExample.js
Improve the styles of the errors that appear below the LiveEditor, for readability.
Just look at the before/after, below:
http://improve-live-editor-error-styles--mineral-ui.netlify.com/
**Before**
**After**
1. Open the site and navigate to a [component page](http://improve-live-editor-error-styles--mineral-ui.netlify.com/components/button)
2. Edit one of the examples such that you get an error
3. Confirm that it's _so_ much more readable and useful and nice now
Docs
> [Website] Improve styles of LiveEditor errors for readability

- src/website/app/App.js
Wrap the app in a `ScrollToTop` component (code from [react-router's site](https://reacttraining.com/react-router/web/guides/scroll-restoration)) that does exactly what it says on the tin.
Navigating to a new page in our site would, frustratingly, remember your scroll position rather than scrolling to the top automatically, as everyone expects. This fixes that.
http://router-scrolling--mineral-ui.netlify.com/getting-started
1. Open the site
2. Scroll down a bit and note what is visible
3. Navigate to another page
4. Confirm that the new page is automatically scrolled to the top
5. Hit the back button
6. Confirm that your scroll position was remembered for the previous page
Docs
In Edge & IE 11, the scroll position is not remembered when going back; it …
> [Site] Force new routed navigations to scroll to top

- src/website/app/App.js
- src/website/app/ComponentDocExample.js
- src/website/app/LiveProvider.js
- src/website/app/Router.js
* Add routed page for each demo example
* Make each example title link to its page
* Add a chromeless mode, triggered by adding "?chromeless" to the end of the URL
* Refactor use of react-live components into a standalone LiveProvider component
* Change ComponentDocExample to a stateless functional component from a class
* Remove un-used Anchor styles in ComponentDocExample and other style improvements
When developing, it can be a pain to have multiple instances of the component on the screen. You could hack around this by editing the examples index, but this is _way_ nicer. The chromeless mode can be used later for visual diff testing.
http://example-permalink--mineral-ui.netlify.com/components/button
Note the URLs here...
1. Open the site and navigate to a [component …
> [Site] Add routed page for each demo example

- src/Card/Card.js
- src/Card/CardImage.js
- src/Dropdown/Dropdown.js
- src/Dropdown/DropdownContent.js
- src/Link/Link.js
- src/Menu/Menu.js
- src/Menu/MenuDivider.js
- src/Menu/MenuGroup.js
- src/Menu/MenuItem.js
- src/ThemeProvider/ThemeProvider.js
- src/website/app/PropTable.js
- src/website/app/demos/Button/examples/iconOnly.js
- src/website/app/demos/Button/examples/icons.js
- src/website/app/demos/Button/examples/rtl.js
- src/website/app/demos/Card/examples/card/card.js
- src/website/app/demos/Card/examples/card/clickable.js
- src/website/app/demos/Card/index.js
- src/website/app/demos/Dropdown/examples/data.js
- src/website/app/demos/Icon/index.js
- src/website/app/demos/Link/bestPractices.js
- src/website/app/demos/Menu/examples/menu-divider/menuDivider.js
- src/website/app/demos/Menu/examples/menu-group/menuGroup.js
- src/website/app/demos/Menu/examples/menu-item/customRender.js
- src/website/app/demos/Menu/examples/menu-item/icons.js
- src/website/app/demos/Menu/examples/menu/data.js
- src/website/app/demos/Menu/examples/menu/menu.js
- Arrays, functions, objects, and unions that are sufficiently complex are displayed as a Button with text content of the type (e.g. “Array”) that opens a Popover displaying the full type information in a more readable manner.
- Fix broken component-to-component links caused by #371
- Improve prop descriptions for various components
- I first tried to put the Popover content in a codeblock with syntax highlighting that matched the others on the site, but it looked terrible inside the Popover.
- The logic to determine whether a type is displayed in a Popover is somewhat arbitrary.
- For most, it’s a simple character count determined by what looks OK in our table at a variety of screen widths. However, this means that our most common Function type, `(event: SyntheticEvent<>) => void`, is …
> [Website] Display complex prop types in Popover

- CHANGELOG.md
- utils/changelogConfig.js
Fix duplicate entries in changelog
* Ensure only new entries will be prepended to the changelog
* Manually update changelog to remove site/website commits
I left the configuration setting in the code in case we need to generate the changelog again from scratch.  Not sure that is entirely necessary, but that configuration setting is really obscure.
Fixes a bug where changelog entries were being duplicated on each release.  Also, this update should allow us to manually edit a changelog and have those changes persisted - e.g. we could provide more detailed upgrade guidelines in the case of a breaking change, etc.
closes #401 
1. checkout the `fix-changelog` branch locally
2. open `scripts/release.js` and add a `process.exit(0)` right before the line that says `// Check if a changelog has …
> docs(changelog): Fix duplicate entries in changelog

- src/website/app/Label.js
- src/website/app/Markdown.js
- src/website/app/MarkdownTable.js
- src/website/app/Nav.js
- src/website/app/Router.js
- src/website/app/pages/ComponentDoc/DocHeader.js
- src/website/app/pages/ComponentStatus/Legend.js
- src/website/app/pages/ComponentStatus/componentStatus.md
- src/website/app/pages/ComponentStatus/index.js
- src/website/app/pages/GettingStarted/gettingStarted.md
- src/website/app/pages/index.js
- src/website/app/tableCellTransforms.js
Create a Component Status page with associated table. **In Development** is defined as "things that are actively being worked on by the dev team". **Planned** are components in the "ready" or "ideas" columns on the [waffle board](https://waffle.io/mineral-ui/mineral-ui)
closes #394 
We would like to let consumers of Mineral UI, internally and externally, know the current state of the development of our component library. Since we're tracking this in several places currently (Trello, Waffle, Invision) this page will provide at-a-glace information to stakeholders and consumers.
https://394-component-status--mineral-ui.netlify.com/
2. Navigate to Component Status
3. are any links missing? anything misspellt?
4. Go through the pages. You should not see the …
> [Website] component status table

- .eslintrc
- package.json
- src/utils/createThemedComponent.js
Get rid of `immutability-helper`
Was causing an error in sample consumer app.
I like the idea of avoiding mutation, but this is the only place where the helper was being used and it feels like overkill to add a dependency just for that.  Alternatively, we could have moved it to runtime dependencies.
We'll need to publish a new release following merge...
https://fix-dependency--mineral-ui.netlify.com/
1. Try to import `createThemedComponent` in a consumer app and see if you get the error.
> fix(utils): Remove immutability-helper from createThemedComponent

- src/website/app/GuidelinePage.js
- src/website/app/Label.js
- src/website/app/MarkdownTable.js
- src/website/app/Nav.js
- src/website/app/Router.js
- src/website/app/pages/ComponentStatus/Legend.js
- src/website/app/pages/ComponentStatus/componentStatus.md
- src/website/app/pages/ComponentStatus/index.js
- src/website/app/pages/index.js
- src/website/app/tableCellTransforms.js
- add hierarchy to pages array (and thus the navigation)
- cleanup design on Component Status page
- move some keys around to fix another markdown error
The Component Status page isn't really a Guideline page, and making the Components header a link isn't super discoverable. This PR adds a couple top-level nav headers to organize things a bit more.
Also some design tweaks so the table (with its icon-only column) doesn't look insane on larger monitors. Deprecate `margin-top` in favor of better css.
https://status-page-tweaks--mineral-ui.netlify.com/
2. Navigate to `/component-status`
3. Check everything out. The table should feel a bit tighter.
- design cleanup
> [Website] Component status page design tweaks

- src/website/app/LiveProvider.js
Fix regression in website code example error display
closes #418 
https://418-live-error-styles--mineral-ui.netlify.com/
1. Go to any code example in the website
1. Add a semicolon in the middle of a tag - in order to throw a syntax error
1. The error message should be nicely formatted and readable underneath the code example, simlar to that shown in the screenshot above
bug fix to the website, so... chore
> chore(website): Fix code example error display

- src/Dropdown/Dropdown.js
- src/Dropdown/DropdownContent.js
- src/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/EventListener/EventListener.js
- src/EventListener/__tests__/EventListener.spec.js
- src/EventListener/index.js
- src/Popover/Popover.js
- src/Popover/PopoverContent.js
- src/Popover/PopoverTrigger.js
- src/Popover/__tests__/Popover.spec.js
- src/Popover/__tests__/__snapshots__/Popover.spec.js.snap
- src/website/app/demos/Dropdown/examples/placement.js
- src/website/app/demos/Dropdown/examples/scrolling.js
- src/website/app/demos/Dropdown/examples/wide.js
- src/website/app/demos/Popover/bestPractices.js
- src/website/app/demos/Popover/examples/controlled.js
- src/website/app/demos/Popover/examples/overflow.js
- src/website/app/demos/Popover/examples/placement.js
- src/website/app/demos/Popover/examples/scrolling.js
- src/website/app/demos/Popover/examples/title.js
This PR extracts the a11y and refactoring improvements from https://github.com/mineral-ui/mineral-ui/pull/414 as the portal related updates are currently blocked by an issue in Popperjs. 
I am not sure how long it may take to get a new version of Popper and I would like to get these  improvements into the codebase sooner rather than later.
connects #395 
https://395-popover-misc--mineral-ui.netlify.com/
1. Mostly just try out Dropdown menus in voiceover.  Focus, nav, and announcements are improved.
_This code has already been reviewed and approved in https://github.com/mineral-ui/mineral-ui/pull/414, so as long as I extracted it cleanly from that PR, we should be good to go._
Little bit of everything - improved a11y, refactoring, updating tests
> [Popover][Dropdown]: Improve a11y

- src/Button/Button.js
- src/Button/__tests__/__snapshots__/Button.spec.js.snap
- src/Card/__tests__/__snapshots__/Card.spec.js.snap
- src/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/Link/__tests__/__snapshots__/Link.spec.js.snap
- src/Popover/__tests__/__snapshots__/Popover.spec.js.snap
- src/styles/createStyledComponent.js
Fixes Dropdown Keyboard nav by making Button only re-render its DOM element when the element prop is changed.  This allows the button to retain focus across renders, which is needed for Dropdown event listeners to function properly.
closes #443
https://443-dropdown-keyboard-nav--mineral-ui.netlify.com/
1. View Dropdown demo
2. Tab to the Button in the first Dropdown example
3. Hit the up or down arrow once to open the Dropdown
4. Hit the up or down arrow again to navigate the menu items
5. View the Button demo
6. Ensure everything behaves as expected
> Fix Dropdown keyboard nav

- jest.config.js
- package.json
- src/Button/Button.js
- src/Button/__tests__/__snapshots__/Button.spec.js.snap
- src/Menu/MenuItem.js
- src/Menu/__tests__/__snapshots__/Menu.spec.js.snap
- src/Menu/__tests__/__snapshots__/MenuItem.spec.js.snap
- utils/setupTestFrameworkScript.js
Adds support for React 16
**This PR does not update the components, local dev environment, or website to use React 16.**  It simply updates the versions in package.json to allow Mineral UI to be consumed in a React 16 app and includes a fix for an issue discovered when testing the package inside of CRA using React 16.
closes #422
https://422-react-16--mineral-ui.netlify.com/
1. Builds and works as normal
2. How I tested in CRA.  Build the package using release script, without publishing.  NOTE: `npm link` doesn't seem to work well here, so...  From mineral-ui/dist, run `npm pack` to generate a tarball. `npm i pathToTarball` in CRA.  Import and render components and ensure all works as expected.  Tested in CRA using React 15.6.1 and React 16.0.0.
Add support …
> Add support for React 16

- __mocks__/popper.js.js
Mock popper.js to avoid console warnings while running tests.
Recently, a bunch of console messages about `document.createRange` began appearing when running the test suite.  These are coming from `popper.js`.  Note, `jsdom` does not support `document.createRange`.
Tried polyfilling `document.createRange`, but it surfaced other issues.  Mocking popper.js is the approach recommended by the popper.js author.
https://create-range-polyfill--mineral-ui.netlify.com/
1. View the travis build build log for this branch or checkout this branch and run `npm run jest`
1. Note the console warnings about `document.createRange` are gone
Removes console warnings during tests
> Mock popper.js to avoid console messages when running tests

- docs/testing.md
- package.json
- scripts/jest-react.js
- utils/setupTestFrameworkScript.js
Add `jest:react` npm script that allows running the jest tests in different versions of react
Helps to detect which React versions mineral-ui will work in.
closes #424 
connects #353 
connects #423
I have intentionally not yet tied the `jest:react` script into the normal testing workflow.  I would like to try it for a while on a manual basis, and if it proves sufficient and non-problematic, then promote it to run automatically **only** on CI.
I believe that this means that we can merge #423, unless we would like to wait until after the new design work has been merged.
I also believe that these tests have likely identified the minimum functioning React version for mineral-ui as `15.3.0`, so we should be able to update and close #353.  I say, "likely", as these tests only catch a certain …
> Add jest:react npm script

- scripts/build-icons.js
Speeds up `build-icons` npm script, thus also speeds up npm installs.  What used to take ~6s now takes <1s.
Noticed the optimization while exploring the possibility of extracting icons to a separate package.  We can get this performance benefit now, without needing to wait for the new package.
https://build-icons--mineral-ui.netlify.com/
1. Compare the speed of either `npm i` or `npm run build:icons` on master vs this branch
1. Ensure all of the icons are still there.
Performance optimization of `build:icons` script
> Optimize glob to speed up build:icons script

- src/website/app/pages/PaletteDemo/ControlPanel.js
- src/website/app/pages/PaletteDemo/Picker.js
- src/website/app/pages/PaletteDemo/index.js
There was a bug in the palette demo where a different color would be shown as active for different screen sizes. This PR fixes that 🐞 
the Picker component was keeping track of its color in state, which was pointless. There are two instances of ControlPanel (and thus Pickers) due to how I'm handling responsive layout. Now there is only one source of truth for `activeColor` in the `PaletteDemo/index` file and it's passed through props.
https://palette-color-bug--mineral-ui.netlify.com/
2. Navigate to the Palette Demo
3. Pick a non-blue color in the sidebar
4. Drag the window until the picker is in the flow of the page (tablet or smaller)
5. Pick a different color. Upon dragging the window to the full width, the active color should stay the same
- Bug fix …
> [Website] fix bug in palette demo

- src/Button/Button.js
- src/Button/__tests__/__snapshots__/Button.spec.js.snap
- src/Card/__tests__/__snapshots__/Card.spec.js.snap
- src/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/Icon/Icon.js
- src/Icon/__tests__/__snapshots__/Icon.spec.js.snap
- src/Link/__tests__/__snapshots__/Link.spec.js.snap
- src/Menu/MenuItem.js
- src/Menu/__tests__/__snapshots__/Menu.spec.js.snap
- src/Menu/__tests__/__snapshots__/MenuDivider.spec.js.snap
- src/Menu/__tests__/__snapshots__/MenuGroup.spec.js.snap
- src/Menu/__tests__/__snapshots__/MenuItem.spec.js.snap
- src/Popover/__tests__/__snapshots__/Popover.spec.js.snap
- src/website/app/Page.js
- src/website/app/demos/Icon/components/Figure.js
- src/website/app/pages/ComponentDoc/DocPractice.js
* Updates the Icon component to use role="img" instead of role="icon"
* Updates other component contextual icon CSS selectors
closes #463 
https://463-icon-role--mineral-ui.netlify.com/
1. Run a a11y check on the Icon demo page using chrome devTools and note that there are no longer any warnings about invalid role attribute on the Icon svg's
2. Add a title and a tabIndex to an Icon component in the demo and verify that it is announced properly, and better than it was previously.
Fixes invalid role attribute
> Improve Icon a11y by using role="img"

- src/Form/FormField.js
- src/Form/FormFieldDivider.js
- src/Form/FormFieldset.js
- src/TextInput/TextInput.js
- src/website/app/demos/Form/examples/form-field-divider/basic.js
- src/website/app/demos/Form/examples/form-field/basic.js
- src/website/app/demos/Form/examples/form-field/caption.js
- src/website/app/demos/Form/examples/form-field/hideLabel.js
- src/website/app/demos/Form/examples/form-field/required.js
- src/website/app/demos/Form/examples/form-field/secondaryText.js
- src/website/app/demos/Form/examples/form-fieldset/basic.js
- src/website/app/demos/Form/index.js
- src/website/app/demos/TextInput/examples/controlled.js
- src/website/app/demos/TextInput/examples/disabled.js
- src/website/app/demos/TextInput/index.js
This PR attempts to align the form component intros and usage sections with our existing copy.
We want to have consistency in our docs.
connect #137
There was plenty of stuff pertaining to forms as a whole that didn't really live on any one component, so I documented it here. https://docs.google.com/document/d/1KDYL35fbqEZqCINzw5h9LpBFoCTKc9LpQNP7LsvMysI/edit
https://textinput-text-input--mineral-ui.netlify.com/
2. View the intro and Usage sections for TextInput, FormField, FormFieldset, FormFieldDivider
3. We want to be prescriptive, but did I talk too much? Did I miss anything?
4. I used the word "grok". Will normal people understand this? It _is_ a page for developers.
- New feature (non-breaking …
> [Website] update intros and usage sections for form components

- src/website/app/pages/ComponentDoc/DocSubNav.js
- src/website/app/pages/ComponentDoc/index.js
closes #506 
This PR makes it so the API & Theme subnav link is _always_ shown on the component page. Also removes some unused variables.
@coldpour noticed that _only_ the CardImage page didn't have the API & Theme link, while the seemingly similar page MenuDivider did show the link. This was because MenuDivider has some theme variables, while CardImage does not. The confusing part is because at some point we made it so the API & Theme header would always show to head up the `CardImage does not have properties of its own. Undocumented properties...` callout that is _always_ shown. Now since that section is always there and contains something, it makes sense to just show the link in the subnav.
I also removed the `hidePropDoc` since we're not using it anywhere. The theory is that we were …
> [Website] enable API & Theme tab for every component

- src/website/app/pages/Home/index.js
remove unused styles from homepage
some styles used to be applied to triangles when they were in an svg element, but now they're a background image so they're not being applied anymore.
https://cleanupstyles--mineral-ui.netlify.com/
2. make sure the homepage looks as expected
- chore
> chore(website): remove unused styles from homepage

- package.json
This version has a bugfix for missing svg images. See
https://github.com/enduire/happo.io/issues/3 for more on the issue.
> build(test): Update to happo.io 0.5.1

- src/website/app/App.js
- src/website/app/Nav.js
- src/website/app/Page.js
- src/website/app/Router.js
- src/website/app/demos/routes.js
The nav currently shows all components in a flat list. This PR will collapse subcomponents under their parent component unless either that parent or a subcomponent is active. It also adds some styles to visually connect those subcomponents to their parent.
Closes #471.
Worth noting:
1. It was decided that our components (so far) require documentation that is too complex to display more than one per page, so we're closing that issue by only updating the navigation.
2. It was also decided that without going "full accordion" with our navigation, we wanted to avoid having two click/tap targets on a menu item to either navigate to that item or expand its subcomponents. Thus, you only see subcomponents after navigating to their parent or a sibling. …
> [Website] Update nav to collapse subcomponents until active

- src/website/app/ComponentDocExample.js
- src/website/app/ErrorBoundary.js
- src/website/app/LiveProvider.js
- Add an ErrorBoundary component and wrap it around our examples' previews/editor
- Fix incorrectly-styled description when viewing standalone example
- Reset text highlight to browser default inside example previews
- Assign funky font-family to live previews to make it immediately
obvious if `includeStyleReset` was forgotten
It can be frustrating to encounter an error while live-editing an example and have the whole page crash. This prevents that and provides a nice "reload this component" button.
The funky font makes it immediately obvious if a dev has forgotten to `includeStyleReset`. If a component can ever be rendered not inside another (i.e. Card, but not CardTitle), then it should have the reset.
The other minor improvements are just things that have been bugging me for a while …
> [website] Add error boundaries for examples & other improvements

- scripts/happo-ci.sh
I've noticed that the comment posted from the happo-ci.sh script can be
noisy, especially for PRs that are pushed to/rebased many times. By
silencing out the comment so that it's only posted when there are one or
more diffs/added/deleted we can avoid noise in many cases.
> build(test): Avoid posting happo comment when no diffs

- src/Avatar/Avatar.js
- src/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
- src/Card/__tests__/__snapshots__/Card.spec.js.snap
Stops the `icon` prop from rendering on the Avatar component DOM element
closes #584
https://584-avatar--mineral-ui.netlify.com/components/avatar/
* View the source of an Avatar component that renders an Icon in the [website](https://584-avatar--mineral-ui.netlify.com/components/avatar/). Note that it no longer contains `icon="[object Object]"`.
* Verify that the `icon` functionality of the Avatar component still works
> [Avatar]: Remove icon prop from rendering on DOM element

- package.json
- src/Dropdown/Dropdown.js
- src/Select/Select.js
Update Select and Dropdown to use `items` instance variable instead of calling `getItems()` a bunch of times.
This does introduce the need to do a deep equality check on `data`, which adds an additional project dependency - https://www.npmjs.com/package/fast-deep-equal
Performance
We wanted to do this in the original Select PR, but it got bumped out of MVP.
http://select-items-instance-var--mineral-ui.netlify.com/
1. General testing - ensure that the Select and Dropdown components work as previous in the demo
2. Additional testing, if you desire...
* start local demo and browse to an individual Select demo example
* add a `console.count('getItems()');` to `Menu.getItems()`;
* play with example and compare the number of times that it is called vs. the same using `master`
* Use …
> perf(select,dropdown) Use items instance var

- package.json
Update prop-types dependency
* Move prop-types package from devDependencies to dependencies
* Use flexible carat version so package can be de-duped in consumer apps 
* Minimum version set to 15.5.7 as previous versions have issues
The package has some pretty clear instructions on how to depend on it.  
https://github.com/facebook/prop-types#how-to-depend-on-this-package
closes #621 
Not sure there is really anything to test here.  We are now strictly following Facebook guidelines on how to depend on this package.  We could maybe go into CRA and validate that different versions get deduped properly, but honestly I am not sure it is worth the effort at this point in time.
Chore, maybe a bugfix, but not one that likely affected anyone yet.
> chore(dependencies): Update prop-types dependency

- docs/publishing.md
- package.json
- scripts/build-library.js
- scripts/build-package.js
- scripts/release.js
Refactor build/release scripts.  Splits apart the release script into different build scripts with individual responsibilities.
Changes:
* `build-library`
* _New_.
* This script simply transpiles the library code to dist.
* Does what `build-package` used to do.  
* `build-package`
* _Changed_.  The previous logic has been moved to the `build-library` script.  The new logic/functionality has been extracted from the `release` script.
* This script determines and updates version in package.json, generates changelog, adds a tag and up to 2 commits (changelog and release), creates a minimal dist/package.json, and creates a locally installable package for testing in CRA.
* The `--label` option is used for generating prerelease packages.  It is used to generate the version and git tag.  e.g. …
> chore(scripts): Improve build/release scripts

- src/library/Select/Select.js
- src/library/Select/__tests__/Select.spec.js
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
Fix Select component to properly call onChange handler when selected item changes.  The comparison was not properly checking the previous selected item.
Connects #645 
You can see the incorrect behavior in the following demo.  Note that the onChange handler is never logged. It uses `mineral-ui@0.22.0`. https://codesandbox.io/s/6wlpo392qr
You can see the corrected behavior in the following demo. Note that the onChange handler is logged.  It uses `mineral-ui@0.23.0-next.0`. 
https://codesandbox.io/s/6z5qk1vz5r
This is the standard mineral website demo using this branch.
https://645-select--mineral-ui.netlify.com/
1. Run the test suite.  There are new unit tests to cover this case.
2. Try out the aforementioned demos.
> fix(select): Select calls onChange handler

- .happo.js
Remove IE from visual regression tests
Testing in IE increases test duration and currently provides little value.
1. Note that happo tests on this PR worked properly
2. Note that the only diffs are to remove IE specific tests
3. Note if the happo test suite ran faster
build/test updates
> test(happo): Remove IE from visual regression tests

- .eslintrc
- src/library/styles/__tests__/pxToEm.spec.js
- src/library/styles/pxToEm.js
BREAKING CHANGE: pxToEm used to disregard all input units and output a value in
ems. now, it only transforms input without units or with px units. bad input
throws an error.
`pxToEm` was untested and once tested, discovered to be relatively unpredictable.
just read the test cases :)
https://pxtoem--mineral-ui.netlify.com/
- Breaking change (fix or feature that would cause existing functionality to change)
> fix(pxToEm): add tests and fix behavior of pxToEm

- src/library/TextInput/TextInput.js
- src/library/TextInput/__tests__/TextInput.spec.js
- src/website/app/demos/TextInput/examples/index.js
- src/website/app/demos/TextInput/examples/types.js
Fix Safari display of search inputs
* Adds dev-only types example to TextInput demo - useful for visual comparison across different browsers
closes #709 
https://709-textinput--mineral-ui.netlify.com/
Validate that Safari now displays TextInputs properly when `type="search"` is specified.
As the types example is dev-only, you'll either need to run the branch locally to use that.  Alternatively, you can just add `type="search"` to any TextInput example.  Alternative to that, Select's [Custom Menu](https://709-textinput--mineral-ui.netlify.com/components/select/custom-menu) example contains a search input and you can just look at that.
> [TextInput] Fix Safari display of search inputs

- src/library/Avatar/Avatar.js
- src/library/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
- src/library/Card/__tests__/__snapshots__/Card.spec.js.snap
- src/library/Menu/__tests__/__snapshots__/Menu.spec.js.snap
Fixes Avatar display of child svg images in IE 11
closes #712 
https://712-avatar--mineral-ui.netlify.com/
1. Do some cross-browser testing - https://712-avatar--mineral-ui.netlify.com/components/avatar
> Fix Avatar display of child svg images in IE 11

- src/library/Checkbox/Checkbox.js
- src/library/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap
- src/library/Checkbox/__tests__/__snapshots__/CheckboxGroup.spec.js.snap
- src/library/Choice/Choice.js
- src/library/Radio/Radio.js
- src/library/Radio/__tests__/__snapshots__/Radio.spec.js.snap
- src/library/Radio/__tests__/__snapshots__/RadioGroup.spec.js.snap
- src/website/app/demos/Checkbox/examples/Checkbox/hideLabel.js
- src/website/app/demos/Checkbox/examples/Checkbox/index.js
- src/website/app/demos/Radio/examples/Radio/hideLabel.js
- src/website/app/demos/Radio/examples/Radio/index.js
Adds a `hideLabel` prop to accessibly hide the label on Radios and Checkboxes
We needed this capability when developing selectable rows in the new Table component.  Agile Central needs this capability for use within their DataTable too.
https://choice-hide-label--mineral-ui.netlify.com/components/checkbox#hide-label
1. Add the `hideLabel` prop to any of the examples in Checkbox, CheckboxGroup, Radio, RadioGroup
2. Ensure that the component size/layout does not shift
3. Try it with a screenreader and verify that the label is announced properly
**BREAKING CHANGES**: Rename theme variables `RadioControl_marginHorizontal`
to `RadioText_marginHorizontal` and `CheckboxControl_marginHorizontal` to
`CheckboxText_marginHorizontal`
> [radio,checkbox]: Add hideLabel prop

- src/library/Checkbox/Checkbox.js
- src/library/Checkbox/CheckboxGroup.js
- src/library/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap
- src/library/Form/__tests__/__snapshots__/FormField.spec.js.snap
- src/library/Form/__tests__/__snapshots__/FormFieldDivider.spec.js.snap
- src/library/Form/__tests__/__snapshots__/FormFieldset.spec.js.snap
- src/library/Radio/Radio.js
- src/library/Radio/RadioGroup.js
- src/library/Radio/__tests__/__snapshots__/Radio.spec.js.snap
- src/library/Select/Select.js
- src/library/Select/SelectTrigger.js
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
- src/library/TextArea/TextArea.js
- src/library/TextArea/__tests__/__snapshots__/TextArea.spec.js.snap
- src/library/TextInput/TextInput.js
- src/library/TextInput/__tests__/__snapshots__/TextInput.spec.js.snap
- src/library/Tooltip/Tooltip.js
- Update Select, TextArea, and TextInput to style a properly themed base component
- Update all other files using `mapComponentThemes` to use a consistent code style
Closes #742 
Specifically, by styling a non-themed base component (FauxControl, in the case of TextInput), we were not supporting any of the theme variables defined on that base component.
https://742-component-themes--mineral-ui.netlify.com/
(_Unfortunately, that link won't help much this time._)
2. Update Select/TextArea/TextInput examples to render a themed version, where the theme sets variables defined by the base component ([TextInput](https://github.com/mineral-ui/mineral-ui/blob/master/src/library/TextInput/TextInput.js#L62-L81) for Select; …
> fix(select,textarea,textinput): Support component-level theme variables

- src/library/Card/CardFooter.js
- Style CardFooter's expand/collapse toggle Button to use variant-appropriate background colors
Closes #740 
https://740-card-footer-variant--mineral-ui.netlify.com/components/card-footer/variants
2. Navigate to CardFooter > Variants
3. Add `expandable` to at least one of the CardFooters rendered
4. Confirm that the hover color is a very light tint of the appropriate variant color
> [Card] Make ToggleButton better respect variant

- src/library/Table/TableCell.js
- src/library/Table/TableHeaderCell.js
- src/library/Table/__tests__/__snapshots__/Table.spec.js.snap
- src/library/themes/mapComponentThemes.js
- Add a `preserveKeys` parameter to `mapComponentTheme` for reason described below
- Refactor rtl-dependent border styles in TableCell & TableHeaderCell
We had an issue reported to us (not on GitHub) where defining both TableCell and TableHeaderCell theme variables would not work correctly; the TableCell theme variables were being applied to TableHeaderCells. After investigation, we determined the details of the root cause and devised a fix.
The fix is needed when both of these are true:
1. Both the themed (TableHeaderCell) and base (TableCell) components need to be independently themeable (e.g. Table exposes theme variables for both)
- At the time of this PR, only Table meets this qualification
2. The base component applies styles using theme variables and the themed …
> [themes][Table] Fix theme overrides

- scripts/build-package.js
- scripts/release.js
* Fix release process by using annotated tag so that follow-tags pushes tag properly.
* This needs tested during the next release
Closes #756 
Not really applicable...
https://756-release-tags--mineral-ui.netlify.com/
During the next release, try it with these changes, and see if this pushed the latest tag automatically.
Fix build/release
> build(release): Use annotated tag so that follow-tags pushes tag properly

- src/library/Pagination/Pages.js
- src/library/Pagination/__tests__/Pagination.spec.js
- src/library/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap
- src/library/Table/__tests__/__snapshots__/Table.spec.js.snap
* Updates the Pagination Pages subcomponent - converts the internal Buttons component to a simple function instead of an actual component.  This way it can still just return an array, without the need for an additional wrapper element.  This means that the DOM structure did not need to change.
* Exclude the Pagination demo example snapshot tests from being tested in older React versions as they use the Table component, which uses the context polyfill, which renders differently in different React versions.
Closes #760
Not really applicable...
http://760-pagination--mineral-ui.netlify.com
1. `npm run jest:react`
> [Pagination]: Render in all supported React versions

- src/website/app/App.js
- src/website/app/Page.js
- src/website/app/Router.js
- src/website/app/demos/routes.js
- src/website/index.js
Clean up demoRoutes usage
* Fix Flow types
* Avoid unnecessary prop passing; now just imported in Router
Extracted this update from my Table render props work
https://routes--mineral-ui.netlify.com/
Just check that you can still navigate around the website.
Just leaving the campsite cleaner than when I arrived... 🏕
> chore(website): Clean up demoRoutes usage

- src/library/Dialog/Dialog.js
Update `Dialog_transitionDuration` theme variable to include units
* More consistent with CSS timing API
* Allows user to specify value in other time units - `s` or `ms`
* Fixes incorrect display of theme variable in website theme documentation, which previously indicated units were px.
Noticed incorrect units in website documentation
https://dialog-transition--mineral-ui.netlify.com/components/dialog#theme-variables
**Before:**
**After:**
* Visit demo and verify change.
* Verify dialog still transitions properly
Fixes website documentation issue by changing a component theme variable value.  The likelihood that someone has overridden this theme variable is remote and combined with the small potential impact leads me to believe that this should not be …
> refactor(dialog): Update Dialog_transitionDuration theme variable to include units

- src/library/Dropdown/Dropdown.js
- src/library/Dropdown/__tests__/Dropdown.spec.js
- src/library/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/library/Menu/Menu.js
- src/library/Menu/MenuItem.js
- src/library/Menu/__tests__/__snapshots__/Menu.spec.js.snap
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
* Small performance improvement in Select/Dropdown when navigating items using arrow keys.  All items used to re-render each time the list was navigated.  Now, only two items re-render, based on the changing `highlightedIndex`.
* Fixes an issue wherein menu item ids weren't being incremented correctly when the data was grouped.  This resulted in multiple items being highlighted simultaneously when navigating w/keyboard.
* connects #679 
* Fixes a bug (no issue number) - described above
https://679-select-dropdown-menu-perf-uno--mineral-ui.netlify.com/
1. Compare the number of MenuItem renders when navigating menu items using keyboard.
1. Add some grouped data, and ensure that the menu item ids increment globally across the groups.  Ensure that only one item is highlighted at a time. There …
> [Dropdown][Select] Perf + Fix

- src/library/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/library/Popover/Popover.js
- src/library/Popover/PopoverTrigger.js
- src/library/Popover/__tests__/__snapshots__/Popover.spec.js.snap
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
- src/library/Tooltip/Tooltip.js
- src/library/Tooltip/__tests__/__snapshots__/Tooltip.spec.js.snap
- src/website/app/demos/Tooltip/examples/cursor.js
- src/website/app/demos/Tooltip/examples/index.js
- Add support for `cursor` prop
- Add example
- Update snapshots (which also affected PopoverTrigger-related render prop snapshots)
Closes #572 
https://572-tooltip-cursor--mineral-ui.netlify.com/components/tooltip
2. Navigate to Tooltip > [Cursor example](https://572-tooltip-cursor--mineral-ui.netlify.com/components/tooltip/cursor)
3. Confirm it works correctly and docs are clear with no typos
> [Tooltip] Add cursor prop

- src/library/Text/ElementContext.js
- src/library/Text/Text.js
- src/library/Text/TextProvider.js
* Update Text and TextProvider to utilize new React Context API
Closes #680 
https://680-text-context--mineral-ui.netlify.com/components/text
1. Navigate to Text > [Nested Components](https://680-text-context--mineral-ui.netlify.com/components/text/nested) section
1. Ensure that styles are as expected
1. Navigate to Text > Nested Elements section (dev-only)
1. Ensure that styles are as expected
- Other: Update to new API so that transition is smoother when the next major version of React is released
> [Text] Update to utilize new React Context API

- src/library/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap
- src/library/Table/TableBase.js
- src/library/Table/TableCell.js
- src/library/Table/TableDataRow.js
- src/library/Table/TableRow.js
- src/library/Table/__tests__/__snapshots__/Table.spec.js.snap
Provides `columnKey` and `rowIndex` to table cells.  Gives user a way to access other data in row, e.g. previous and next cells.
This feature has been requested by users for use with custom cell renderers.
Is it sufficient to provide `rowIndex` and `columnKey` or do we need to provide `rowData`?  Here, we provide the indexes instead of a data object in order to attempt to avoid unnecessary cell re-renders when any row data is changed.   With the current solution, there is no danger of unnecessary re-rendering and the `rowIndex` and `columnKey` can be used to look up information in the main data source.
https://table-row-index--mineral-ui.netlify.com/components/table/
1. Go to the [custom cell](https://table-row-index--mineral-ui.netlify.com/components/table/custom-cell) example.
2. Add …
> [Table]: Add columnKey and rowIndex to table rows and cells

- .babelrc.js
Enable component prop-types to be removed in user apps during production mode minification
I noticed that Mineral prop-types were still in code when using CRA in production mode.
We were previously applying [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) only to the website as we want to ship prop-types for components.  Using the plugins `wrap` option however, we can apply this to the components as well.  This wraps the prop-type definitions in a process.env.NODE_ENV check, enabling their continued use by users in development, but stripping them out in production, during minification, thus resulting in smaller bundles.
https://transform-proptypes--mineral-ui.netlify.com/
1. Checkout the …
> [Perf] Transform Component PropTypes

- src/library/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap
- src/library/Menu/MenuItem.js
- src/library/Menu/__tests__/__snapshots__/Menu.spec.js.snap
- src/library/Menu/__tests__/__snapshots__/MenuDivider.spec.js.snap
- src/library/Menu/__tests__/__snapshots__/MenuGroup.spec.js.snap
- src/library/Menu/__tests__/__snapshots__/MenuItem.spec.js.snap
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
- Assign correct colors to MenuItem backgroundColor theme variables
Self-discovered bug.
https://fix-menu-item-background-color--mineral-ui.netlify.com/components/dropdown
1. Navigate to [Dropdown](https://fix-menu-item-background-color--mineral-ui.netlify.com/components/dropdown) and hover over various items
1. Confirm that hovered (or keyboard selected) items have a light gray background color
> [Menu] Fix MenuItem background color

- src/library/index.js
Fix error when importing from package index.
It looks like this is some sort of dependency resolution order issue.  This probably isn't a great solution, but rather a quick fix for the immediate problem.  I'll continue to do some more investigation in/after the `ez-grok` work.
Closes #791 
https://791-import-error--mineral-ui.netlify.com/
1. Checkout the `791-import-error` branch
1. Build local mineral-ui package and import it in latest CRA
1. Add `import * as mineral from 'mineral-ui';  console.log(mineral);` to App.js
1. View App in production mode (`npm run build && serve -s build`) and ensure that there are no console errors.
> Fix error when importing from package index

- src/library/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap
- src/library/Select/SelectTrigger.js
- src/library/Select/__tests__/__snapshots__/Select.spec.js.snap
Fix `Select`'s click to open in Edge
It was reported that a `Select` component in a `FormField` did not open on a single click using Edge.  The issue can be replicated here.  https://mineral-ui.com/components/select/form-field
It turns out that the hidden input element inside of the `SelectTrigger` was bubbling click events, causing the `Select` to open and immediately close.  This was resolved by stopping the propagation of the hidden input's click event.
https://select-fix-edge--mineral-ui.netlify.com/components/select/form-field
Browse to the demo example link above, using MS Edge, and verify that `Select` opens on a single mouse click.
> [Select] Fix click to open in Edge

- src/library/Card/__tests__/__snapshots__/Card.spec.js.snap
- src/library/Card/__tests__/__snapshots__/CardBlock.spec.js.snap
- src/library/Card/__tests__/__snapshots__/CardDivider.spec.js.snap
- src/library/Card/__tests__/__snapshots__/CardImage.spec.js.snap
- src/library/Card/__tests__/__snapshots__/CardStatus.spec.js.snap
- src/library/Card/__tests__/__snapshots__/CardTitle.spec.js.snap
- src/library/Card/styled.js
- src/library/Popover/__tests__/__snapshots__/Popover.spec.js.snap
Ensure icons stay same size when resize Card
CardTitle icons were noticed to shrink when a Card was resized.  The issue can be replicated by viewing https://mineral-ui.com/components/card-title/variants and resizing the window.
https://cardtitle-icons--mineral-ui.netlify.com/components/card-title/variants
Visit the demo link above and ensure that the icons in the CardTitle stay the same size when the window is resized.
> [CardTitle] Ensure icons stay same size when resize Card

- package.json
- src/library/Table/Selectable.js
- src/library/Table/Table.js
- src/library/Table/__tests__/Table.spec.js
- src/library/Table/utils.js
Updates `Table` legacy React lifecycle methods
Closes #764 
Connects #652
_Definitely some more deepEquals calls in here.  Open to suggestions on how to minimize them further..._
https://764-table-lifecycle--mineral-ui.netlify.com/
1. Should be no change in functionality.
1. Works in React < 16.3. (I tested in CRA with React 16.2.0)
Refactor
> [Table] Legacy React lifecycle migration

- src/library/Box/propTypes.js
- src/library/Box/types.js
- src/library/Dialog/__tests__/__snapshots__/Dialog.spec.js.snap
- src/library/Dialog/__tests__/__snapshots__/DialogActions.spec.js.snap
- src/library/Dialog/__tests__/__snapshots__/DialogBody.spec.js.snap
- src/library/Dialog/__tests__/__snapshots__/DialogFooter.spec.js.snap
- src/library/Dialog/__tests__/__snapshots__/DialogHeader.spec.js.snap
- src/library/Dialog/__tests__/__snapshots__/DialogTitle.spec.js.snap
- src/library/Dialog/styled.js
- src/library/Flex/__tests__/__snapshots__/FlexItem.spec.js.snap
- src/library/Flex/propTypes.js
- src/library/Flex/styled.js
- src/library/Flex/types.js
- src/website/app/demos/Dialog/Dialog/examples/composition.js
- src/website/app/demos/Flex/FlexItem/examples/index.js
- src/website/app/demos/Flex/FlexItem/examples/minWidth.js
- src/website/app/demos/Flex/FlexItem/propDocs.js
* Add `minWidth` prop to FlexItem
* Add demo example
* Fix additional layout issues
* Ensure DialogBody & FlexItem children do not extend beyond element boundary
* Update Dialog Composition example to illustrate layout scenario
Fix issues reported by users in chat.
https://layout-bugs--mineral-ui.netlify.com/components/flex-item/min-width
1. Navigate to FlexItem > [Min Width example](https://layout-bugs--mineral-ui.netlify.com/components/flex-item/min-width)
1. Confirm that the Select is truncated properly
1. Navigate to Dialog > Composition example (only viewable locally)
1. Confirm that the Select is truncated properly
- Feature
> [Dialog] [Flex] Fix layout issues

- package.json
- packages/mineral-ui-icons/package.json
- packages/mineral-ui-icons/scripts/build.js
- packages/mineral-ui-tokens/package.json
- packages/mineral-ui-tokens/scripts/build.js
Ensure sub-package (`mineral-ui-icons` and `mineral-ui-tokens`) builds respect root babel config
Sub-package build steps were no longer respecting the root `babel.config.js`.  This was broken during a recent babel update.
https://babel-packages--mineral-ui.netlify.com/
1. `cd packages/mineral-ui-icons` & `cd packages/mineral-ui-tokens`
2. `DEBUG=true npm run build`
3. Build should succeed and debug output should be logged
Fixes an issue with the sub-packages build configuration
> build(packages): Ensure sub-package builds respect babel config

- src/library/Navigation/Navigation.js
Update Navigation so that `restProps` is no longer spread onto NavItem children.
Closes #827
https://nav-item-props--mineral-ui.netlify.com/components/primary-nav/basic
1. Navigate to [PrimaryNav](https://nav-item-props--mineral-ui.netlify.com/components/primary-nav/basic)
1. Add an undocumented valid prop (e.g. `role="foo"`) to PrimaryNav and confirm that it does not spread onto NavItem children
- Breaking change (fix or feature that would cause existing functionality to change)
BREAKING CHANGE: PrimaryNav & SecondaryNav no longer passes along 
undocumented props to NavItem
> [Navigation] Prevent spread of Navigation parent props onto NavItem

- src/library/themes/themeFromTokens.js
Currently, the `fontSize_base` theme variable is documented as `'1em'`, despite being used as `'16px'` throughout our styles. This PR updates the docs to display the value as `'16px'`.
Closes #826
https://font-size-base-docs--mineral-ui.netlify.com/theming#typography
2. Navigate to [Theming](https://font-size-base-docs--mineral-ui.netlify.com/theming#typography) and scroll down to fontSize_base, under Typography
3. Confirm that the value displayed is "16px"
Just a simple docs update; the functional code is untouched. Not sure if this should be considered a breaking change, as consumers may have attempted to use `em` units for this theme variable prior to this change. Since that would not have worked, I'm assuming no one other …
> docs(theme): Keep px units for fontSize_base
