.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, ROADMAP.md
Updates various documentation files for the repo. This still contains some commented-out bits that aren’t yet applicable or known.
This will help inform stakeholders and future contributors. It also helps us build and maintain a welcoming, inclusive community and values transparency as we intend to do.
- Non-source (for changes that don’t affect the source code, e.g. documentation)
=> Update repo docs

packages/archetype/README.md, packages/hello-world/README.md, packages/hello/README.md, packages/world/README.md
each component README has 
* a link to the top level README
* installation steps with npm
* sample jsx showing the usage of the component
the current README files were empty and need something in them so that people can consume our components
i created a react app and pulled in all the components and tested that they showed up in the browser.
i wish i had a way to template these READMEs...
=> docs - add component READMEs

README.md, ROADMAP.md
* Updates the readme and roadmap docs
connects #18
[n/a]
Documentation
=> Documentation updates - readme and roadmap

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Added a link to our Waffle board to CONTRIBUTING.md and removed the ‘—’ from the titles in the issue and PR templates.
Further exposure of our project board, and the dashes weren’t necessary.
Docs
=> Small docs improvements

.babelrc, package.json
Added babel plugin to perform react component optimizations.
Could potentially improve performance.
https://medium.com/doctolib-engineering/improve-react-performance-with-babel-16f1becfaa25
Build and tests passed.
=> perf(react): Add babel plugins to optimize react components

README.md, packages/archetype/.npmignore, packages/archetype/webpack.config.js, packages/hello-world/.npmignore, packages/hello-world/webpack.config.js, packages/hello/.npmignore, packages/hello/webpack.config.js, packages/site/src/__demo__/index.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap, packages/site/webpack.config.js, packages/style-utils/.npmignore, packages/world/.npmignore, packages/world/src/__demo__/examples/world.js, packages/world/webpack.config.js
Cleans up some leftover code cruft
No one likes cruft
closes #51
* Builds properly, tests pass, package contents correct, site works
Minor cleanup
=> [All] Clean up cruft

packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap, packages/style-utils/src/Sample.js, packages/style-utils/src/__demo__/examples/createStyledComponent.js, packages/style-utils/src/__tests__/ThemeProvider.spec.js, packages/style-utils/src/__tests__/__snapshots__/ThemeProvider.spec.js.snap, packages/style-utils/src/__tests__/__snapshots__/createThemedComponent.spec.js.snap, packages/style-utils/src/__tests__/createThemedComponent.spec.js, packages/style-utils/src/mineralTheme.js, packages/style-utils/src/styleVariables.js
- Add proper structure to styleVariables and mineralTheme files
- Update Sample component and some examples to reflect new structure
Connects to #45 
We need Mineral UI's default theme to be real, so we can start building components.
Manually confirmed that the Sample component renders correctly.
=> [Theme]: Add proper structure to styleVariables and mineralTheme

docs/styling.md
* Validated with potential contributors and consumers
* Includes a ‘Using Themes’ section
Connects #22 
We need to document our component styling strategy, so that it is understood and usable by both contributors and consumers.
We asked three developers to attempt to build a couple components using our style-utils and updated the documentation based on their experiences and comments/suggestions.
Docs
=> Update styling docs

package.json
update glamorous to version 3.23.3
the library published a new version
we ran the demo
=> chore(package): update glamorous to version 3.23.3

package.json
when switching between branches that have different packages, flow will report false errors because dist is still around from the previous branch where the source has been removed. our previous solution of having each package clean itself is insufficient becuase a package that doesn't exist can't clean up after itself. since all source is in the packages directory, and a subsequent build command will rebuild the correct package dist from source, the clean command can and should remove all dist directories from packages.
running `npm run build` over and over 
=> chore(scripts): make clean work across branches

scripts/package/build.sh, utils/makeWebpackConfig.js
this webpack flag broke our hot reloading when tested on the button component
=> build(webpack): remove scope hoisting

README.md, packages/site/src/components/siteTheme.js, packages/site/src/web/index.html
install Open Sans font in our site and add it to our font-family
our design system / style guide is based off Open Sans
ran the demo
=> [Theme] install Open Sans

packages/archetype/src/__demo__/index.js, packages/hello-world/src/__demo__/index.js, packages/hello/src/__demo__/index.js, packages/site/src/components/ComponentDoc.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap, packages/style-utils/src/__demo__/index.js, packages/world/src/__demo__/index.js
link to readme for how to install/use
we already have installation and usage instructions in the readme for each component. let's not
repeat ourselves unneccesarily.
ran the demo and the tests. updated snapshots
=> feat(site): link to readme for how to install/use

packages/button/src/__demo__/index.js, packages/component-utils/src/__demo__/index.js, packages/hello-world/src/__demo__/index.js, packages/hello/src/__demo__/index.js, packages/site/src/__demo__/index.js, packages/site/src/components/App.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap, packages/world/src/__demo__/index.js
fixes routing when running the site for a single component
running the site for a single component demo was broken after switching the routing to use a hash
lookup because a single demo object wasn't also keyed by it's slug. now by adding the slug back into the demo object, if the demo object passed into the app has a slug, it's a single demo. otherwise, it's assumed to be an object where the key is the slug and the value is a demo object.
running the site at the top level and at the button level and `npm test`
=> fix(site): single component demo routing

packages/site/src/components/App.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
when you go to mineral-ui.com, redirect to button instead of hello
people should see a real component when they show up on the site instead of a dummy one
ran the demo locally and went to the root - saw that the redirect worked
=> feat(site): change home page redirect from hello to button

docs/publishing.md
Adds tips to publishing docs.
There are some gotcha's during the publishing process that can be helpful to be aware of.
n/a
docs
=> docs(publishing): Add publishing tips

.eslintrc
Update eslint configuration to support es6
* `es6: true` - adds new globals, such as `Map`, `Set`, and `Promise`
* `ecmaVersion: 2016` - updates syntax
* See http://eslint.org/docs/user-guide/configuring#specifying-parser-options
I was working on a node script for the forthcoming Icon component and tried to use `Set` and `Promise` and `eslint` complained about them not being defined.
No eslint errors when using `Map`, `Set`, `Promise`, etc.
configuration update
=> [eslint] Update configuration to support es6

packages/card/package.json, packages/card/src/__demo__/examples/card-block/arbitraryChildren.js, packages/card/src/__demo__/examples/card-block/cardBlock.js, packages/card/src/__demo__/examples/card-image/withImage.js, packages/card/src/__demo__/examples/card-title/complexTitle.js, packages/card/src/__demo__/examples/card-title/minor.js, packages/card/src/__demo__/examples/card-title/withSubtitle.js, packages/card/src/__demo__/examples/card/arbitraryChildren.js, packages/card/src/__demo__/examples/card/card.js, packages/card/src/__demo__/examples/card/orderOfSections.js
@kylegach Let's discuss
connects #142
=> Help fix flow errors on the card branch

packages/button/src/__demo__/examples/danger.js, packages/button/src/__demo__/examples/disabled.js, packages/button/src/__demo__/examples/sizes.js, packages/button/src/__demo__/examples/states.js, packages/button/src/__demo__/examples/success.js, packages/button/src/__demo__/examples/truncation.js, packages/button/src/__demo__/examples/warning.js, packages/button/src/__tests__/__snapshots__/Button.spec.js.snap, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
Change `Root` in the example source to be `DemoLayout` in most cases and `FixedWidthLayout` when that was instructive.
`Root` doesn't mean anything and I imagine it will confuse people. Adding a descriptive name is a simple way to provide clarity.
connects #29
ran the demo, snapshots updated
refactor
=> feat(site): Make live code examples more readable

.github/PULL_REQUEST_TEMPLATE.md
provide a place for submitters to note exactly how to replicate the features added for potential
reviewers
Embellished the testing section in this GitHub PR template. So meta.
This would help the team check everything that's covered in our PRs, especially the bigger ones. Even more important, once we have community submissions, it's going to be important that we know what to check when going through code from people we haven't directly spoken with.
no tests. I live on the edge.
- Other
docs.
=> [Docs]: change testing section of PR template

packages/button/package.json, packages/button/src/Button.js, packages/button/src/__demo__/examples/circular.js, packages/button/src/__demo__/examples/iconOnly.js, packages/button/src/__demo__/examples/icons.js, packages/button/src/__demo__/examples/index.js, packages/button/src/__demo__/examples/rtl.js, packages/button/src/__tests__/__snapshots__/Button.spec.js.snap, packages/card/src/__tests__/__snapshots__/Card.spec.js.snap, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
enable icon buttons by passing in an instance of an Icon component
https://github.com/mineral-ui/mineral-ui/issues/77
We added the ability to render an Icon in a button component by passing `<IconExample />` into a button by exposing an `icon` attribute that accepts `MnrlReactNode`. Doing it this way as opposed to passing in a string prevents the Button component from having to load every Icon component into memory (and presumably into the build).
There's no reason that we couldn't pass a string in the future once tree-shaking is working better.
connects #77
closes #153 
We had a Button and we had an Icon, it's a match made in heaven.
- visual testing in browsers
- `npm run test`
=> [Button] enable buttons with icon

packages/card/src/CardTitle.js, packages/card/src/__demo__/components/DemoLayout.js, packages/card/src/__demo__/examples/card-block/arbitraryChildren.js, packages/card/src/__demo__/examples/card-block/cardBlock.js, packages/card/src/__demo__/examples/card-image/withImage.js, packages/card/src/__demo__/examples/card-title/complexTitle.js, packages/card/src/__demo__/examples/card-title/minor.js, packages/card/src/__demo__/examples/card-title/withMetaInfo.js, packages/card/src/__demo__/examples/card-title/withSubtitle.js, packages/card/src/__demo__/examples/card/card.js, packages/card/src/__demo__/examples/card/orderOfSections.js, packages/card/src/__tests__/__snapshots__/Card.spec.js.snap, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
- Add support for meta information
- Add demo meta info demo example
- Refactor examples to use a shared DemoLayout
The style guide specifies that CardTitle needs to optionally display a category title. Also, though the style guide specifies a version of the Card/CardTitle that has an avatar, we have opted to not yet build that functionality, as the design is very much in flux.
Confirmed to render correctly in all supported browsers.
=> [CardTitle] Additional functionality

docs/discussions/git-workflow.md
Add document describing outcome of a discussion regarding a proposed new git workflow.
As a Mineral UI developer, I would like an improved git workflow, so that I have more control over the release process.
closes #199 
n/a
docs
=> Add discussion document describing alternate git workflow proposal

packages/card/src/Card.js, packages/card/src/__demo__/examples/card/clickable.js, packages/card/src/__demo__/examples/card/index.js, packages/card/src/__tests__/Card.spec.js, packages/card/src/__tests__/__snapshots__/Card.spec.js.snap, packages/card/src/cardTheme.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
- Add onClick prop to Card
- Add keyboard support (enter & space)
- Add cursor style when onClick is provided
- Add focus style
Closes #194 
Consumers sometimes need their users to be able to click the entire Card.
1. `cd mineral-ui/packages/card && npm start`
1. Find the With onClick example
1. Click the Card
1. Click and hold on the Card then drag your mouse off and release (or find some other way to focus it)
1. Press Enter
1. Press Space
1. Check the console for the event being logged
=> [Card] Add onClick prop and focus style

docs/discussions/process.md
add a doc to capture information about our team's process
we had a few conversations about improving various parts of our process. it will be good to keep track of what we've decided on so that we can refer back to it and onboard new people should the need arise.
=> docs(process): add process doc

packages/link/.npmignore, packages/link/LICENSE.md, packages/link/README.md, packages/link/package.json, packages/link/src/Link.js, packages/link/src/__demo__/examples/children.js, packages/link/src/__demo__/examples/index.js, packages/link/src/__demo__/examples/link.js, packages/link/src/__demo__/examples/reactRouter.js, packages/link/src/__demo__/examples/states.js, packages/link/src/__demo__/index.js, packages/link/src/__tests__/Link.spec.js, packages/link/src/__tests__/__snapshots__/Link.spec.js.snap, packages/link/src/index.js, packages/link/webpack.config.js, packages/site/src/components/ComponentDoc.js, packages/site/src/components/Footer.js, packages/site/src/components/Nav.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap
Added a Link component. This really just a wrapper around an `<a>` since we don't want to re-invent the wheel re: keyboard events, a11y, etc.
closes #149 
We decided that Link needs to be a separate component than Button, since a button is a form element, while an anchor is not.
1. `npm run build`
2. navigate to Site > Link
3. Play with the links and make sure all the normal props are passed thru
4. It's pretty much just an anchor tag
- New feature
=> WIP: [Link] component

docs/discussions/gatsby.md
Did some research on Gatsby and set up several demos - recommend not using Gatsby in the short term.
Findings in the markdown.
Added `gatsby.md` to `/docs/discussions/`
We wanted to know if we could use Gatsby to stand up a site quickly for CA World. Now we know.
- Docs
=> [Docs]: Gatsby-as-site research write-up

packages/card/src/CardTitle.js
I think the title covers it. This pattern should be used on all public components.
Closes #229 
See #229 
1. Pass CardTitle a `className` (or any other non-specified, valid DOM) prop in a consuming app
1. Confirm that prop is rendered correctly in the DOM
=> [Card] Pass all props to underlying root component

docs/site-map.md
This is a roadmap for the site MVP. I'm resurrecting a super old issue so there's at least a paper trail.
closes #43 
"Wow," you may be thinking to yourself, "this issue is super old". That's a fair assesment! I'm making this doc as a jumping off point for future stories, and as a reference for myself. Mostly this document is going to serve as a map for what's going to be in the MVP site, and we're going to expand on it as we go along.
We need to know what content we need to fill into the demo site, allowing us to rattle our sabres at the right people.
1. read the sitemap.md if you please.
- Docs
=> [Docs]: create a site map

packages/site/src/components/App.js, packages/site/src/components/Header.js, packages/site/src/components/Nav.js, packages/site/src/components/PageLayout.js, packages/site/src/components/TopLevelNav.js, packages/site/src/components/__tests__/__snapshots__/App.spec.js.snap, packages/site/src/pages/Color.js, packages/site/src/pages/Community.js, packages/site/src/pages/GettingStarted.js, packages/site/src/pages/TableOfContents.js, packages/site/src/pages/Theming.js, packages/site/src/pages/Typography.js, packages/site/src/pages/WhatsNext.js, packages/site/src/pages/index.js, packages/site/src/pages/pages.js
This PR is mostly structural changes and filler content to set up later development of Guidelines pages.
closes #225 
- created a `/packages/site/src/pages` folder that will hold some (all?) of the top-level content
- stopgap `SideNav.js` component
We can merge this into `master` and even publish the site if we so choose; the router has not been changed and the site still goes from `/` to `/components/button`.
We need to block out areas were we need content provided to us by other teams. In lieu of design comps, we can at least create the IA for the demo site and copy can be refined as we go along. Creating pages will get the conversation moving about what content needs to go where.
The extra pages are currently quite ugly, so I'm going to hide behind this door 🚪 
1. fire up the site like …
=> [Site] restructure site components to enable building guidelines pages

.github/PULL_REQUEST_TEMPLATE.md
- Update **How to test** section with a comment about testing in a sandbox (i.e. not just the demo) for new components and breaking changes
- Make improvements to existing **How to test** content, including moving the list out of the comment
- Replace smart quotes with dumb ones, for consistency
In some scenarios, testing outside of the demo needs to be part of our process. This change serves as a reminder.
[How about a link to a nice preview, instead?](https://raw.githubusercontent.com/mineral-ui/mineral-ui/0fc308a5793f02cfbaa003df106f7db60070b954/.github/PULL_REQUEST_TEMPLATE.md)
Docs
=> Update PR template, specifically 'How to test'

package.json
With the switch to Netlify, we no longer need to manually deploy the site after release via the CLI. Instead, Netlify’s continuous deployment will automatically deploy when the chore(publish) commit is merged into master.
It’s wasteful to deploy the same thing twice. Also, authentication can be an issue for the CLI deploy.
1. `cd mineral-ui && npm run release:semantic`
1. Step through options
1. Confirm that `netlify deploy` never runs
1. Confirm that the site still deployed via continuous deployment
Build-related
=> Remove CLI deploy from release:semantic

packages/button/src/Button.js, packages/button/src/__tests__/__snapshots__/Button.spec.js.snap, packages/card/src/__tests__/__snapshots__/Card.spec.js.snap
Add `alignItems: 'center'` to Button Inner styles, to ensure proper vertical alignment.
Closes #253 
1. `cd mineral-ui/packages/button && npm start`
2. Change the the icon size to `small` when the Button size is `jumbo`:
```js
const iconSize = {
// ...
jumbo: 'small'
};
```
3. Confirm that alignment is correct.
4. Remove the modification above.
5. Confirm that alignment is correct.
=> [Button]: Fix vertical alignment

src/Button/__tests__/__snapshots__/Button.spec.js.snap, src/Card/__tests__/Card.spec.js, src/Card/__tests__/__snapshots__/Card.spec.js.snap, src/Icon/__tests__/__snapshots__/Icon.spec.js.snap, src/Link/__tests__/Link.spec.js, src/Link/__tests__/__snapshots__/Link.spec.js.snap, src/Popover/__tests__/Popover.spec.js, src/Popover/__tests__/__snapshots__/Popover.spec.js.snap, src/ThemeProvider/__tests__/__snapshots__/ThemeProvider.spec.js.snap, src/utils/__tests__/__snapshots__/createThemedComponent.spec.js.snap, src/utils/__tests__/createThemedComponent.spec.js, utils/enzymeUtils.js, utils/testDemoExamples.js
Minor testing improvements
* Add describe block around demo examples
* Add enzymeUtils
* Update snapshots
Makes tests nicer to work with...
`npm test`
Minor test utils updates
=> [utils] Minor testing improvements

src/website/app/pages/Typography/FontDemo.js, src/website/app/pages/Typography/examples.js, src/website/app/pages/Typography/index.js, src/website/app/pages/Typography/typography.md, src/website/app/pages/index.js
connects #240
Create a Typography page with demos and a list of related tokens.
We'd like to document the design system thinking with regard to Typography. This guideline page attempts to show designers what the thought process is in choosing our fonts, and how to choose different styles for different intentions when designing a UI. For (theme) developers, we provide some style hook documentation.
2. Navigate to Typography in the side menu
3. Look over the content. Are there spelling errors or inconsistencies?
=> [Website] typography page

README.md, src/website/index.html
The meta description tag provides a description on the search engine results page so users will know what Mineral UI is all about. The README.md file was updated so consumers that come across our repo will see the same information.
closes #330 
The `<meta description="foo">` tag is what provides content for search engine result descriptions. If you don't provide this tag, the page is scraped and some random information is filled in. In our case, it was some code examples from the getting started page.
Content is:
```
Mineral UI is a design system and React component library for the web that lets you quickly build high-quality, accessible apps. Created by CA Technologies.
```
If we don't provide this content manually, it will change over time as we re-structure the page or could become …
=> [Website] update the meta description tag for search results

src/website/app/GuidelinePage.js, src/website/app/Markdown.js, src/website/app/pages/Color/index.js, src/website/app/pages/ComponentDoc/DocHeader.js, src/website/app/pages/Typography/index.js
wrap the GuidelinePage component around Color and Type content.
the GuidelinePage component enables styling on the paragraphs following the h1 and preceding the first h2 (the lede). after the component was added to the getting started and theming pages, I forgot to wrap it around Color and Typography.
connects #390 
2. Color and Typography pages should have the same larger font size on the intro as Getting Started and Theming.
=> [Website] font size and margin tweaks

.github/PULL_REQUEST_TEMPLATE.md
Add a starter link, `https://<your-branch-name>--mineral-ui.netlify.com/`, to the PR template.
Deploy previews are awesome and helpful and we should encourage sharing of them.
Docs
=> chore(docs): Update PR template to include starter demo link

.github/ISSUE_TEMPLATE.md
Update outdated Versions section
* Update Versions section as components are no longer independently versioned.
* Separate out environment comment to a new Environment section.
The `Versions` section was out of date and really only made sense when the components were individually versioned.  The environment comment that was in there, didn't really seem to fit so I split it out into its own section.
Just review the text changes...
documentation update
=> docs(issue-template): Update outdated Versions section

package.json, src/website/app/App.js, src/website/index.html, webpack.config.js
Added Google [Global Site Tag](https://developers.google.com/analytics/devguides/collection/gtagjs/) tracking code to the site. For example, this will let you turn on AdWords, Search Console, or [Optimize to run experiments](https://support.google.com/360suite/optimize/answer/7513085) (that page says "in beta" but the Analytics dashboard says "recommended" for gtag.js) or something from the Google suite of tools. With this you don't have to clutter up the index file with more code snippets. 
**Note** third-party tags will still have to be injected manually. If we want to use Google Tag Manager to do that at some point, we have the option to do so.
I set some exclusions in the Analytics admin interface so we won't see traffic from the deploy previews.
Since we have an SPA, I set a hook on …
=> [Website] add analytics

src/Button/Button.js, src/Button/__tests__/__snapshots__/Button.spec.js.snap, src/Link/__tests__/__snapshots__/Link.spec.js.snap, src/website/app/demos/Button/examples/index.js, src/website/app/demos/Button/examples/link.js, src/website/app/demos/Button/examples/primary.js, src/website/app/demos/Link/examples/button.js
* Fix an issue with Button type prop filtering.  Button was rendering `type="button"` on links.
* Add examples with Button rendering as link primarily so that we use snapshot tests to prevent regressions here.
The type props was not being filtered properly on the Button component when rendered as a link.
https://fix-button--mineral-ui.netlify.com/
1. View demo
2. Note the new examples - "Button > link" & "Link > button"
3. Inspect the DOM element in of the aforementioned examples and note that it does not have the `type="button"` attribute on it
4. Edit the live Button > link example and change the type to something that is valid on a link, such as `type="text/html"` and note that it is allowed.
It  is a bug fix for the Button …
=> [Button]: Fix an issue with type prop filtering

package.json
Update minimum React/ReactDOM peer dependency version
_It is likely that Mineral UI works in a lower version of React as well, but we do not currently have the infrastructure to test/support it.  Anecdotally, all tests passed and package was fully functional in React 15.4.2.  We may update this version to be more accurate in the future as we develop more automated testing solutions in this area._
closes #353
https://413-minimum-react-version--mineral-ui.netlify.com/
1. This is our current version of react, so there should be no additional testing needed.
1. I tested by installing and importing mineral components into CRA running React 15.6.1.
Sort of a bug fix
=> Update minimum React/ReactDOM peer dependency version

package.json, src/themes/createColorRamp.js, src/themes/createTheme.js, src/website/app/Heading.js, src/website/app/pages/Color/ColorRamp.js, src/website/app/pages/Color/index.js, src/website/app/pages/PaletteDemo/ColorRamp.js, src/website/app/pages/PaletteDemo/ControlPanel.js, src/website/app/pages/PaletteDemo/Demo.js, src/website/app/pages/PaletteDemo/Picker.js, src/website/app/pages/PaletteDemo/gallery.md, src/website/app/pages/PaletteDemo/index.js, src/website/app/pages/PaletteDemo/paletteDemo.md, src/website/app/pages/Styling/index.js, src/website/app/pages/Theming/index.js, src/website/app/pages/Theming/theming.md, src/website/app/pages/index.js
closes #379 
Create a new page to show off how our components react to Mineral color changes. 
We wanted a flashier way to show off styling and how easy it is to work with ThemeProvider.
https://379-theme-demo--mineral-ui.netlify.com/
2. Navigate to `/palette-demo` or click the cta Button on the Theming or Styling pages
3. Click around. Is everything smooth-ish? Are the transitions nice?
4. Does the copy on the page make sense?
- NOT a new feature (non-breaking change which adds functionality)
Adds a new page to the website
=> [Website]: Palette demo

src/website/app/pages/index.js
I forgot to add the Palette demo link to the main nav after our discussion, and remembered right after I clicked the button to merge the Palette Demo PR. _This_ PR adds that feature.
Do we want to have the Palette demo linked from somewhere other than the CTA on the Theming page? Is Customization the right place to put this link? 
https://palette-demo-link-in-nav--mineral-ui.netlify.com/
2. Click the link in the side nav for Palette Demo
3. Does it work?
- not a new feature (non-breaking change which adds functionality)
=> [Website] add Palette Demo link to side nav

src/website/app/pages/ComponentDoc/DocPractice.js
The green/red Do/Don't Best Practices blocks require special attention for inline code and links, not to mention quite a lot of type-specific styling. I realized I could use ThemeProvider and greatly simplify the styling approach.
I kept coming across edge cases that were missed. This should make things "just work".
https://best-practice-link-color--mineral-ui.netlify.com/
2. Navigate to Dropdown > Best Practices
3. Notice that the link is the right color
4. Navigate to CardImage > Best Practices
5. Notice that the inline code is the right color
Just a small website improvement.
=> [Website] Improve Best Practices Do & Don't block styles

src/website/app/App.js, src/website/app/Page.js, src/website/app/Router.js, src/website/app/demos/Icon/index.js, src/website/app/demos/routes.js, src/website/app/pages/ComponentDoc/DocProps.js, src/website/app/pages/GettingStarted/gettingStarted.md, src/website/app/pages/Home/index.js, src/website/app/pages/index.js, src/website/index.html
closes #495 
This PR adds the ability for each page to have a separate `<meta>` description.
Meta descriptions are no longer _super_ important in google's algorithm, but they remain important because it's what the user reads on the search result page to determine whether they'll click on a link or not.
https://495-meta-description--mineral-ui.netlify.com/
2. Navigate to any page (or all pages)
3. the meta description should be unique for each page, and reflect its content
- website upgrade
=> [Website] unique meta descriptions

src/website/app/pages/Roadmap/roadmap.md
talked to @Mikewaite and we came up with these updates to our roadmap
it's been a while since we published these and we've done some things since then
https://<your-branch-name>--mineral-ui.netlify.com/
2. Navigate to Button > Buttons with kittens section
3. Click the Cat Button twice (three times in IE 11)
4. ¡Hear the cat meow en Español!
=> chore(website): update roadmap page

src/website/app/demos/Button/bestPractices.js, src/website/app/demos/Card/bestPractices.js, src/website/app/demos/Dropdown/bestPractices.js, src/website/app/demos/Icon/bestPractices.js, src/website/app/demos/Link/bestPractices.js, src/website/app/demos/Menu/bestPractices.js, src/website/app/demos/Popover/bestPractices.js, src/website/app/demos/ThemeProvider/bestPractices.js, src/website/app/pages/ComponentDoc/DocPractice.js
- Remove/merge Best Practice title into description
- Re-order some Best Practices
- Flip variant examples so that `success` goes with "do" and `danger` goes with "don't"
- Remove margins on `pre` inside Best Practice examples
- Update secondary text examples to match OS X standard
Closes #473; closes #440
https://473-best-practices--mineral-ui.netlify.com/
2. Navigate to each component and ensure their Best Practices section has correct content and examples, free of errors
Website docs
=> [Website] Update Best Practices content

src/website/app/pages/Home/content/structuredData.json, src/website/app/pages/Home/index.js
closes #494 
This PR adds [structured data](https://developers.google.com/search/docs/guides/intro-structured-data) ([JSON-LD](https://json-ld.org/)) to the home page.
We'd like search results for Mineral UI to show more detailed information for users. The way that you do this is expose an [accepted schema](https://schema.org/) of our website data to users (and implicitly search engines).
I'm not _positive_ this is going to work on the first go. There's some conflicting information, especially about the SiteNavigationElement. Some of our peers have this data exposed (especially the detail stuff on the right of the screenshot) but this information is scraped from Wikipedia's quick facts section. We don't have a Wikipedia article (yet) so this is the next best thing. …
=> [Website] add structured data to homepage

src/website/app/pages/Home/index.js
update blog post link
connects #481 
https://update-blog--mineral-ui.netlify.com/
click the blog post link and make sure the spelling is right
chore
=> chore(website): update blog post link

src/website/app/pages/Styling/styling.md
capitalize the component names
the component name was lower case and they are usually upper case
https://capitalize-component-name--mineral-ui.netlify.com/styling/
please don't bother
chore
=> chore(website): components should have capital letters

src/Select/Select.js
Update Select description in website header
=> chore(website): update Select description

src/website/app/pages/ComponentStatus/componentStatus.md
http://component-status--mineral-ui.netlify.com/component-status/
=> chore(website): update component status page

src/website/index.html, src/website/public/noscript.html
_See title_
Closes #466 
https://466-noscript--mineral-ui.netlify.com/noscript.html
1. Open https://466-noscript--mineral-ui.netlify.com and confirm it loads as expected
1. Disable JS and reload that page (or any other)
1. Confirm that you're redirected to https://466-noscript--mineral-ui.netlify.com/noscript.html
Just website stuff.
=> [website] Add noscript.html & noscript redirect

src/website/app/Page.js, src/website/app/Router.js, src/website/app/pages/NotFound/index.js, src/website/app/pages/NotFound/notFound.md
- Add 404 page route
- Add redirects for cases like /components/not-a-route & /components/box/not-an-example
Note: We looked at Netlify to see what it would take to [add a custom 404 server-side](https://www.netlify.com/docs/redirects/#custom-404). Since that would require generating a static 404.html file, we decided the JS-dependent version was fine.
Closes #547
- https://547-404-page--mineral-ui.netlify.com/404
- https://547-404-page--mineral-ui.netlify.com/components
- https://547-404-page--mineral-ui.netlify.com/components/not-a-component
- https://547-404-page--mineral-ui.netlify.com/components/button/not-an-example
1. For the four links above:
1. The first should show a fun 404
1. The second should redirect to avatar (the first component)
1. The third should redirect to avatar (the …
=> [website] 404 page and other route considerations

src/library/Card/CardFooter.js, src/library/Card/CardTitle.js, src/library/Card/__tests__/__snapshots__/Card.spec.js.snap, src/library/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap, src/library/Checkbox/__tests__/__snapshots__/CheckboxGroup.spec.js.snap, src/library/Dropdown/__tests__/__snapshots__/Dropdown.spec.js.snap, src/library/Form/FormField.js, src/library/Form/FormFieldset.js, src/library/Form/__tests__/__snapshots__/FormField.spec.js.snap, src/library/Menu/MenuGroupTitle.js, src/library/Menu/MenuItem.js, src/library/Menu/__tests__/__snapshots__/Menu.spec.js.snap, src/library/Menu/__tests__/__snapshots__/MenuDivider.spec.js.snap, src/library/Menu/__tests__/__snapshots__/MenuGroup.spec.js.snap, src/library/Menu/__tests__/__snapshots__/MenuItem.spec.js.snap, src/library/Radio/__tests__/__snapshots__/RadioGroup.spec.js.snap, src/library/Select/__tests__/__snapshots__/Select.spec.js.snap, src/library/TextArea/__tests__/__snapshots__/TextArea.spec.js.snap, src/library/TextInput/__tests__/__snapshots__/TextInput.spec.js.snap
- Update component-level theme variables and some styles to reference the newly-available theme variables for things like `color_h5` & `fontWeight_h6`.
- Update some styles to be more systematic
Closes #593 
https://593-text-propagation--mineral-ui.netlify.com/components/card-title
1. Navigate to the changed components
1. [CardFooter](https://593-text-propagation--mineral-ui.netlify.com/components/card-footer)
1. [CardTitle](https://593-text-propagation--mineral-ui.netlify.com/components/card-title)
1. [FormField](https://593-text-propagation--mineral-ui.netlify.com/components/form-field)
1. [FormFieldset](https://593-text-propagation--mineral-ui.netlify.com/components/form-fieldset)
1. [MenuGroup](https://593-text-propagation--mineral-ui.netlify.com/compone …
=> [Card] [Form] [Menu] Reference global theme variables

src/library/Text/Text.js, src/library/Text/TextProvider.js, src/library/index.js
- Include missing exports for Card subcomponents
- Update Text components to use the prop-types package for context types.
Using prop-types was the intended method in #648, but somehow a different method was shipped accidentally.
https://text-context--mineral-ui.netlify.com/
2. Navigate to Text with your console open
3. Confirm no errors
4. Spin up a CRA sandbox and try to do named imports for CardActions, CardDivider, CardFooter, and CardTitleMenu
- Fix
Refactor
=> [Card] [Text] Fix missing exports, use prop-types for context types

src/library/Checkbox/__tests__/__snapshots__/Checkbox.spec.js.snap, src/library/FauxControl/FauxControl.js, src/library/Form/__tests__/__snapshots__/FormField.spec.js.snap, src/library/Form/__tests__/__snapshots__/FormFieldDivider.spec.js.snap, src/library/Form/__tests__/__snapshots__/FormFieldset.spec.js.snap, src/library/Radio/__tests__/__snapshots__/Radio.spec.js.snap, src/library/Select/SelectTrigger.js, src/library/Select/__tests__/__snapshots__/Select.spec.js.snap, src/library/TextArea/TextArea.js, src/library/TextArea/__tests__/__snapshots__/TextArea.spec.js.snap, src/library/TextInput/TextInput.js, src/library/TextInput/__tests__/__snapshots__/TextInput.spec.js.snap, src/website/app/LiveProvider.js
- Refactor TextArea to use FauxControl, like Select & TextInput
- Extract height styles from FauxControl into SelectTrigger & TextInput, to keep the responsibility where it should be
- Fix z-index bug with TextArea when placed in a container with a background color
- Fix disabled text color bug in Safari (and many mobile Android browsers)
- Update snapshots of affected examples
- Always apply a background color (white, by default, but still configurable for cases like Card's examples) to the LivePreview, to catch z-index issues in the future
Discovered the z-index bug ([you can see the issue here](https://codesandbox.io/s/wk431361n7)) and decided to use the opportunity to refactor rather than merely applying 'zIndex: 1` to TextArea's root. Then discovered the disabled text color Safari …
=> [Select] [TextArea] [TextInput] Refactor to use FauxControl; fix z-index bug

.happo.js, package.json
This is a duplicate PR for https://github.com/mineral-ui/mineral-ui/pull/671 
It is necessary to submit the PR from an internal team member in order to kick off Happo tests.
See the original PR for more details.
=> test(happo): Update to happo.io 1.2.0

src/library/themes/mapComponentThemes.js
`mapComponentThemes` returns an object with a few things spread into it. It used to spread the baseTheme first, this PR changes it to spread last.
Prior to this change, you could not override the component-level theme variables for any component built using `mapComponentThemes`.
https://map-component-themes--mineral-ui.netlify.com/
1. Choose one or more of the components that uses `mapComponentThemes` (Checkbox, CheckboxGroup, Radio, RadioGroup, Select, TextArea, TextInput, Tooltip)
1. Render that component inside a ThemeProvider with a custom theme overriding one or more of that component's theme variables, e.g.
```jsx
// In some page...
<ThemeProvider theme={{ CheckboxControl_backgroundColor_checked: 'rebeccapurple' }}>
<Checkbox name="test" label="Test" …
```
=> [themes] Ensure base theme overrides component theme when using mapComponentThemes

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, docs/README.md
* Remove all indications that we are no longer accepting contributions
* Add links to our CodeSandbox Mineral UI Starter
* Add PR example & PR alternate form of sharing
* Add links to developer docs
Closes #519 
https://519-update-contributing--mineral-ui.netlify.com/
- Other: documentation updates
=> chore(documentation): Remove "Not accepting contributions" messages

src/library/Box/Box.js, src/library/Flex/Flex.js, src/library/Flex/FlexItem.js, src/library/Flex/__tests__/Flex.spec.js, src/library/Flex/__tests__/FlexItem.spec.js, src/library/Flex/__tests__/__snapshots__/Flex.spec.js.snap, src/library/Flex/__tests__/__snapshots__/FlexItem.spec.js.snap, src/library/Grid/__tests__/__snapshots__/Grid.spec.js.snap, src/library/Grid/__tests__/__snapshots__/GridItem.spec.js.snap, src/library/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap, src/library/StartEnd/__tests__/__snapshots__/StartEnd.spec.js.snap, src/library/Table/__tests__/__snapshots__/Table.spec.js.snap, src/library/styles/getResponsiveStyles.js, src/website/app/demos/Flex/components/Flex.js, src/website/app/demos/Flex/examples/Flex/alignItems.js, src/website/app/demos/Flex/examples/Flex/boxProps.js, src/website/app/demos/Flex/examples/Flex/direction.js, src/website/app/demos/Flex/examples/Flex/rtl.js, src/website/app/demos/Flex/examples/FlexItem/boxProps.js, src/website/app/demos/Flex/examples/FlexItem/flexProps.js, src/website/app/demos/Flex/examples/FlexItem/index.js, src/website/app/demos/Flex/index.js, src/website/app/demos/Grid/components/Grid.js, src/website/app/demos/Grid/examples/Grid/boxProps.js, src/website/app/demos/Grid/examples/GridItem/boxProps.js
- Refactor Flex's gutters
- To better respect RTL and responsive properties
- To remove the outer negative margins, which had caused layout issues for consumers and was a prerequisite for...
- Add a `flex` prop to FlexItem to compose Flex instead of Box, which makes it much easier to nest flex containers and flexed items for layout purposes
- Simplify the demo-only styles for Flex, which fixed #710 
- Add some specs for critical/complex functionality
- Pagination snapshots were affected because it uses Flex components
- Table snapshots were affected because the controlled examples use Flex components
Closes #706, closes #710, closes #711
https://flex-improvements--mineral-ui.netlify.com/components/flex
2. Navigate to …
=> [Flex,FlexItem] Flex gutter refactor & improvements; FlexItem can be a Flex

src/library/Pagination/__tests__/__snapshots__/Pagination.spec.js.snap, src/library/Table/Sortable.js, src/library/Table/TableHeaderCell.js, src/library/Table/__tests__/__snapshots__/Table.spec.js.snap, src/website/app/demos/Table/examples/sortable.js, src/website/app/demos/Table/examples/sortableControlled.js, src/website/app/demos/Table/examples/sortablePaginated.js
- Prevent Tables with a controlled `sort` from sorting the data internally (see breaking change, below)
- Update examples & docs necessarily
- Fix a small visual issue with sortable header cells where the dotted border was displaying over the focus outline
Closes #752 
https://752-sortable-improvements--mineral-ui.netlify.com/components/table/sortable-paginated
2. Navigate to Table > [Sortable — Controlled](https://752-sortable-improvements--mineral-ui.netlify.com/components/table/sortable-controlled) & [Sortable — Paginated](https://752-sortable-improvements--mineral-ui.netlify.com/components/table/sortable-paginated) examples
3. Confirm it works properly
- Breaking change (fix or feature that would cause existing functionality to change)
Breaking: Tables …
=> [Table] Improve sorting

CONTRIBUTING.md, docs/rfcs/_new-component.md
Add new component RFC template and update contributing doc.
Process improvement
* Identify component APIs prior to development
* Help facilitate external contributions
Github documentation updates
=> Add new component RFC template and update contributing doc

docs/rfcs/header.md
RFC for Header component
Document approach and solicit feedback prior to implementation
=> [Header] New component RFC

README.md, src/website/app/pages/GettingStarted/gettingStarted.md, src/website/app/pages/Home/content/getStarted.md
supersedes #807   updated changes to follow mineral contribution guide. Let me know if I can help any other way. Thanks for you time 🤗
=> [Docs] added fix across website and readme for emotion

CONTRIBUTING.md
=> Fix RFC link
